# Deploying Wazuh 4.14.6

This guide documents how I deployed **Wazuh 4.14.6** on **Ubuntu Server 24.04.4 LTS** as the Security Information and Event Management (SIEM) platform for my SOC Automation project.

Instead of reproducing the official installation guide, I followed the Wazuh documentation and focused this guide on verifying the deployment, configuring the environment, and integrating Wazuh with the remaining SOC components.

> **Official Installation Guide**
>
> https://documentation.wazuh.com/current/installation-guide/index.html

---

# Environment

| Component | Version |
|-----------|---------|
| Ubuntu Server | 24.04.4 LTS |
| Wazuh Manager | 4.14.6 |
| Wazuh Dashboard | 4.14.6 |
| Wazuh Indexer | 4.14.6 |
| Windows Endpoint | Windows 10 |
| Sysmon | Sysinternals Sysmon |

---

# Architecture

<p align="center">
<img src="../screenshots/soc-automation-architecture.png" width="900">
</p>

<p align="center">
<em><strong>Figure 1.</strong> SOC Automation Architecture showing Wazuh integrated with Shuffle SOAR, VirusTotal, TheHive and Email notifications.</em>
</p>

---

# Deployment

I deployed Wazuh using the **official Wazuh Installation Assistant**.

The deployment automatically installed:

- Wazuh Manager
- Wazuh Dashboard
- Wazuh Indexer

Rather than reproducing the installation commands, please refer to the official Wazuh documentation linked above.

---

# Extract Installation Credentials

After installation completed successfully, I extracted the credentials generated by the installation assistant.

```bash
sudo tar -xvf wazuh-install-files.tar
```

These credentials were used to log into the Wazuh Dashboard.

---

# Verify the Wazuh Installation

To verify that Wazuh had been deployed correctly, I checked the installed version.

```bash
sudo /var/ossec/bin/wazuh-control info
```

Output:

```text
WAZUH_VERSION="v4.14.6"
WAZUH_REVISION="rc2"
WAZUH_TYPE="server"
```

This confirms that the Wazuh Manager was successfully deployed.

---

# Access the Dashboard

Open a browser.

```
https://<WAZUH_SERVER_IP>
```

The login page should appear.

<p align="center">
<img src="../screenshots/wazuh-login-page.png" width="900">
</p>

<p align="center">
<em><strong>Figure 2.</strong> Wazuh Dashboard login page.</em>
</p>

---

# Dashboard Overview

After authentication, I verified that the dashboard was operational.

<p align="center">
<img src="../screenshots/wazuh-dashboard-overview.png" width="900">
</p>

<p align="center">
<em><strong>Figure 3.</strong> Wazuh Dashboard after a successful deployment.</em>
</p>

---

# Install the Windows Agent

After deploying the manager, I installed the Wazuh Agent on the Windows 10 endpoint and connected it to the Wazuh Manager.

This enabled endpoint telemetry to be forwarded into the SIEM.

---

# Install Sysmon

To improve endpoint visibility, Microsoft Sysmon was installed on the Windows endpoint.

Sysmon provides detailed logging for:

- Process Creation
- Network Connections
- Driver Loading
- Registry Events
- File Creation

---

# Verify Sysmon Telemetry

After configuring the Wazuh Agent and Sysmon, I confirmed that Sysmon events were successfully ingested into Wazuh.

<p align="center">
<img src="../screenshots/wazuh-sysmon-events.png" width="900">
</p>

<p align="center">
<em><strong>Figure 4.</strong> Sysmon events successfully collected by Wazuh.</em>
</p>

---

# Custom Detection Rules

Once telemetry was available, I created custom Wazuh rules to detect Mimikatz execution.

These custom detections formed the basis of the SOC automation workflow documented later in this project.

---

# Troubleshooting

During deployment I verified:

- Wazuh version
- Dashboard accessibility
- Manager service
- Windows Agent connectivity
- Sysmon event collection
- Dashboard indexing

---

# References

Official Wazuh Documentation

https://documentation.wazuh.com/current/installation-guide/index.html

---

# Next Step

With Wazuh successfully deployed and endpoint telemetry verified, the next stage is configuring **Shuffle SOAR** to automate alert enrichment, email notifications, and incident creation in TheHive.

➡ Continue to **03-Configure-Shuffle.md**
